module PureMVC

  class Mediator < Notifier

    include _IMediator

    NAME: String

    attr_reader name: String

    attr_accessor component: Object?

    def initialize: (?String? name, ?Object? component) -> void
  end

  # Type-level assertion that Mediator conforms to _IMediator
  type mediator_validation = validate_mediator[Mediator]
end
