module PureMVC
  # A base <code>_IMediator</code> implementation.
  #
  # @see View
  class Mediator < Notifier

    include _IMediator

    # The name of the <code>Mediator</code>.
    #
    # Typically, a <code>Mediator</code> will be written to serve
    # one specific control or group controls and so,
    # will not have a need to be dynamically named.
    NAME: "Mediator"

    @name: String
    # @return [String] The name of the Mediator.
    attr_reader name: String

    @view: Object?
    # @return [Object, nil] The view component associated with this Mediator.
    attr_accessor view: Object?

    # Initializes a new Mediator instance.
    #
    # @param name [String | nil] the name of the mediator (default: <code>NAME<code>)
    # @param view [Object, nil] the view component this mediator manages (default: <code>nil</code>)
    # @return [void]
    def initialize: (String? name, Object? view) -> void

    # Returns an array of notification names this mediator is interested in.
    #
    # @return [Array<String>] list of notification names
    def list_notification_interests: () -> Array[String]

    # Handles a notification.
    #
    # @param notification [_INotification] the notification to handle
    # @return [void]
    def handle_notification: (_INotification notification) -> void

    # Called when the mediator is registered.
    # @return [void]
    def on_register: () -> void

    # Called when the mediator is removed.
    # @return [void]
    def on_remove: () -> void
  end
end
