module PureMVC
  # A Multiton <code>_IView</code> implementation.
  #
  # In PureMVC, the <code>_IView</code> class assumes these responsibilities:
  #
  # - Maintains a cache of <code>_IMediator</code>instances.
  # - Provides methods for registering, retrieving, and removing <code>_IMediators</code>.
  # - Notifies <code>_IMediators</code>when they are registered or removed.
  # - Manages the observer lists for each <code>_INotification</code>in the application.
  # - Provides a method for attaching <code>_IObservers</code>to an <code>_INotification</code>'s observer list.
  # - Provides a method for broadcasting an <code>_INotification</code>.
  # - Notifies the <code>IObservers</code>of a given <code>_INotification</code>when it is broadcast.
  #
  # @see Mediator
  # @see Observer
  # @see Notification
  class View

    include _IView

    # The Multiton IModel instanceMap.
    # @return [Hash{String => _IView}]
    self.@instance_map: Hash[String, _IView]

    # Mutex used to synchronize access to the instance map for thread safety.
    # @return [Mutex]
    self.@mutex: Mutex

    @multiton_key: String

    # Mapping of Notification names to Observer lists
    @observer_map: Hash[String, _IObserver]

    # Mutex used to synchronize access to the observer_map
    @observer_mutex: Mutex

    # Mapping of Mediator names to Mediator instances
    @mediator_map: Hash[String, _IMediator]

    # Mutex used to synchronize access to the mediator_map
    @mediator_mutex: Mutex

    MULTITON_MSG: "View instance for this Multiton key already constructed!"

    # The Multiton IModel instanceMap.
    # @return [Hash{String => _IView}]
    def self.instance_map: () -> Hash[String, _IView]

    private

    # Mutex used to synchronize access to the instance map for thread safety.
    # @return [Mutex]
    def self.mutex: () -> Mutex

    public

    # View Multiton Factory method.
    #
    # @param key [String]
    # @return [IView] the Multiton instance of <code>View</code>
    def self.get_instance: (String key) { () -> _IView } -> _IView

    # Remove an <code>_IView</code> instance.
    #
    # @param key [String] the key of the <code>_IView</code> instance to remove
    # @return [void]
    def self.remove_view: (String key) -> void

    # Constructor.
    #
    # This <code>_IView</code> implementation is a Multiton,
    # so you should not call the constructor directly.
    # Instead, call the static Multiton factory method <code>View.get_instance(multiton_key) { |key| View.new(key) }</code>.
    #
    # @param key [String]
    # @return [void]
    # @raise [RuntimeError] if an instance for this Multiton key has already been constructed.
    def initialize: (String key) -> void

    # Initialize the Multiton <code>View</code> instance.
    #
    # Called automatically by the constructor, this
    # is your opportunity to initialize the Multiton
    # instance in your subclass without overriding the
    # constructor.
    #
    # @return [void]
    def initialize_view: () -> void

    # Register an <code>_IObserver</code> to be notified
    # of <code>_INotifications</code> with a given name.
    #
    # @param notification_name [String] the name of the <code>_INotifications</code> to notify this <code>_IObserver</code> of
    # @param observer [_IObserver] the <code>_IObserver</code> to register
    # @return [void]
    def register_observer: (String notification_name, _IObserver observer) -> void

    # Notify the <code>_IObservers</code> for a particular <code>_INotification</code>.
    #
    # All previously attached <code>_IObservers</code> for this <code>_INotification</code>'s
    # list are notified and are passed a reference to the <code>_INotification</code> in
    # the order in which they were registered.
    #
    # @param notification [_INotification] the <code>_INotification</code> to notify <code>_IObservers</code> of.
    # @return [void]
    def notify_observers: (_INotification notification) -> void

    # Remove the observer for a given notifyContext from an observer list for a given Notification name.
    #
    # @param notification_name [String] which observer list to remove from
    # @param notify_context [Object] remove the observer with this object as its notifyContext
    # @return [void]
    def remove_observer: (String notification_name, Object notify_context) -> void

    # Register an <code>_IMediator</code> instance with the <code>View</code>.
    #
    # Registers the <code>_IMediator</code> so that it can be retrieved by name,
    # and further interrogates the <code>_IMediator</code> for its
    # <code>_INotification</code> interests.
    #
    # If the <code>_IMediator</code> returns any <code>_INotification</code>
    # names to be notified about, an <code>Observer</code> is created encapsulating
    # the <code>_IMediator</code> instance's <code>handleNotification</code> method
    # and registering it as an <code>Observer</code> for all <code>_INotifications</code> the
    # <code>_IMediator</code> is interested in.
    #
    # @param mediator [_IMediator] a reference to the <code>_IMediator</code> instance
    # @return [void]
    def register_mediator: (_IMediator mediator) -> void

    # Retrieve an <code>_IMediator</code> from the <code>View</code>.
    #
    # @param mediator_name [String] the name of the <code>_IMediator</code> instance to retrieve.
    # @return [_IMediator, nil] the <code>_IMediator</code> instance previously registered with the given <code>mediatorName</code>.
    def retrieve_mediator: (String mediator_name) -> _IMediator?

    # Check if a Mediator is registered or not.
    #
    # @param mediator_name [String] the name of the mediator to check.
    # @return [Boolean] whether a Mediator is registered with the given <code>mediatorName</code>.
    def has_mediator?: (String mediator_name) -> bool

    # Remove an <code>_IMediator</code> from the <code>View</code>.
    #
    # @param mediator_name [String] name of the <code>_IMediator</code> instance to be removed.
    # @return [_IMediator, nil] the <code>_IMediator</code> that was removed from the <code>View</code>, or nil if none found.
    def remove_mediator: (String mediator_name) -> _IMediator?
  end

  # Type-level assertion that View conforms to _IView
  type view_validation = validate_view[View]
end
