module PureMVC
  # The interface definition for a PureMVC Facade.
  #
  # The Facade Pattern suggests providing a single
  # class to act as a central point of communication
  # for a subsystem.
  #
  # In PureMVC, the Facade acts as an interface between
  # the core MVC actors (<code>Model</code>, <code>View</code>, <code>Controller</code>) and
  # the rest of your application.
  #
  # @see IModel
  # @see IView
  # @see IController
  # @see ICommand
  # @see INotification
  interface _IFacade

    # Register an <code>_ICommand</code> with the <code>Controller</code>.
    #
    # @param notification_name [String] the name of the <code>_INotification</code> to associate the <code>_ICommand</code> with.
    # @param factory [^() -> _ICommand] the factory to produce an instance of the _ICommand
    def register_command: (String notification_name) { () -> _ICommand } -> void

    # Check if a Command is registered for a given Notification
    #
    # @param notification_name [String]
    # @return [Boolean] whether a Command is currently registered for the given <code>notification_name</code>.
    def has_command?: (String notification_name) -> bool

    # Remove a previously registered <code>_ICommand</code> to <code>_INotification</code> mapping from the Controller.
    #
    # @param notification_name [String] the name of the <code>_INotification</code> to remove the <code>_ICommand</code> mapping for
    def remove_command: (String notification_name) -> void

    # Register an <code>_IProxy</code> with the <code>Model</code> by name.
    #
    # @param proxy [_IProxy] the <code>_IProxy</code> to be registered with the <code>Model</code>.
    def register_proxy: (_IProxy proxy) -> void

    # Retrieve a <code>IProxy</code> from the <code>Model</code> by name.
    #
    # @param proxy_name [String] the name of the <code>_IProxy</code> instance to be retrieved.
    # @return [_IProxy | nil] the <code>IProxy</code> previously registered by <code>proxy_name</code> with the <code>Model</code>.
    def retrieve_proxy: (String proxy_name) -> _IProxy?

    # Check if a Proxy is registered
    #
    # @param proxy_name [String]
    # @return [Boolean] whether a Proxy is currently registered with the given <code>proxy_name</code>.
    def has_proxy?: (String proxy_name) -> bool

    # Remove an <code>_IProxy</code> instance from the <code>Model</code> by name.
    #
    # @param proxy_name [String] the <code>_IProxy</code> to remove from the <code>Model</code>.
    # @return [_IProxy | nil] the <code>_IProxy</code> that was removed from the <code>Model</code>
    def remove_proxy: (String proxy_name) -> _IProxy?

    # Register an <code>_IMediator</code> instance with the <code>View</code>.
    #
    # @param mediator [_IMediator] a reference to the <code>_IMediator</code> instance
    def register_mediator: (_IMediator mediator) -> void

    # Retrieve an <code>_IMediator</code> instance from the <code>View</code>.
    #
    # @param mediator_name [String] the name of the <code>_IMediator</code> instance to retrieve
    # @return [_IMediator | nil] the <code>_IMediator</code> previously registered with the given <code>mediator_name</code>.
    def retrieve_mediator: (String mediator_name) -> _IMediator?

    # Check if a Mediator is registered or not
    #
    # @param mediator_name [String]
    # @return [Boolean] whether a Mediator is registered with the given <code>mediator_name</code>.
    def has_mediator?: (String mediator_name) -> bool

    # Remove an <code>_IMediator</code> instance from the <code>View</code>.
    #
    # @param mediator_name [String] name of the <code>IMediator</code> instance to be removed.
    # @return [_IMediator | nil] the <code>_IMediator</code> instance previously registered with the given <code>mediator_name</code>.
    def remove_mediator: (String mediator_name) -> _IMediator?

    # Initialize this _INotifier instance.
    #
    # This is how a </code>Notifier</code> gets its multitonKey.
    # Calls to <code>send_notification</code> or to access the
    # facade will fail until after this method has been called.
    #
    # @param key [String] The multitonKey for this INotifier to use.
    def initialize_notifier: (String key) -> void

    # Notify <code>Observer</code>s.
    #
    # This method is left public mostly for backward
    # compatibility and to allow you to send custom
    # notification classes using the facade.
    #
    # Usually you should call sendNotification
    # and pass the parameters, never having to
    # construct the notification yourself.
    #
    # @param notification [_INotification] the <code>_INotification</code> to have the <code>View</code> notify <code>Observers</code> of.
    def notify_observers: (_INotification notification) -> void

    # Send a <code>_INotification</code>.
    #
    # Convenience method to prevent having to construct new
    # notification instances in our implementation code.
    #
    # @param name [String] The name of the notification to send.
    # @param body [Object, nil] The body of the notification (optional).
    # @param type [String, nil] The type of the notification (optional).
    def send_notification: (String name, ?Object? body, ?String? type) -> void
  end

  type validate_facade[Facade < _IFacade] = top
end
