module PureMVC
  # The interface definition for a PureMVC Notifier.
  #
  # <code>MacroCommand, Command, Mediator</code> and <code>Proxy</code>
  # all have a need to send <code>Notifications</code>.
  #
  # The <code>_INotifier</code> interface provides a common method called
  # <code>sendNotification</code> that relieves implementation code of
  # the necessity to actually construct <code>Notifications</code>.
  #
  # The <code>Notifier</code> class, which all the above-mentioned classes
  # extend, also provides an initialized reference to the <code>Facade</code>
  # Singleton, which is required for the convenience method
  # for sending <code>Notifications</code>, but also eases implementation as these
  # classes have frequent <code>Facade</code> interactions and usually require
  # access to the facade anyway.
  #
  # @see IFacade
  # @see INotification
  interface _INotifier
    # Initialize this _INotifier instance.
    #
    # This is how a </code>Notifier</code> gets its multitonKey.
    # Calls to <code>send_notification</code> or to access the
    # facade will fail until after this method has been called.
    #
    # @param key [String] The multitonKey for this INotifier to use.
    def initialize_notifier: (String key) -> void

    # Send a <code>_INotification</code>.
    #
    # Convenience method to prevent having to construct new
    # notification instances in our implementation code.
    #
    # @param name [String] The name of the notification to send.
    # @param body [Object, nil] The body of the notification (optional).
    # @param type [String, nil] The type of the notification (optional).
    def send_notification: (String name, ?Object? body, ?String? type) -> void

    # Return the Multiton Facade instance
    #
    # @raise [RuntimeError] if the <code>multiton_key</code> is not set
    # @return [_IFacade] the facade instance for the notifier's key
    def facade: () -> _IFacade
  end

  type validate_notifier[Notifier < _INotifier] = top
end
